export const MATERIAL_ICONS_LIST = [
    'search', 'home', 'menu', 'close', 'settings', 'check_circle', 'favorite', 'add', 'delete', 'arrow_back',
    'star', 'chevron_right', 'logout', 'arrow_forward_ios', 'add_circle', 'cancel', 'arrow_back_ios',
    'arrow_forward', 'arrow_drop_down', 'more_vert', 'check', 'check_box', 'toggle_on', 'grade', 'open_in_new',
    'check_box_outline_blank', 'refresh', 'login', 'chevron_left', 'radio_button_unchecked', 'more_horiz',
    'apps', 'radio_button_checked', 'download', 'remove', 'toggle_off', 'bolt', 'arrow_upward', 'filter_list',
    'delete_forever', 'autorenew', 'key', 'sort', 'sync', 'arrow_downward', 'add_box', 'block', 'restart_alt',
    'menu_open', 'shopping_cart_checkout', 'expand_less', 'circle', 'arrow_right_alt', 'backspace', 'arrow_circle_right',
    'done_all', 'expand_more', 'undo', 'do_not_disturb_on', 'open_in_full', 'double_arrow', 'manage_search',
    'sync_alt', 'zoom_in', 'done_outline', 'drag_indicator', 'fullscreen', 'keyboard_double_arrow_right',
    'star_half', 'ios_share', 'settings_accessibility', 'arrow_drop_up', 'reply', 'exit_to_app', 'unfold_more',
    'library_add', 'cached', 'terminal', 'select_check_box', 'change_circle', 'disabled_by_default', 'swap_horiz',
    'swap_vert', 'app_registration', 'download_for_offline', 'close_fullscreen', 'file_download', 'minimize',
    'keyboard_double_arrow_left', 'open_with', 'keyboard_double_arrow_down', 'add_task', 'dataset', 'keyboard_voice',
    'start', 'create_new_folder', 'forward', 'downloading', 'settings_applications', 'compare_arrows', 'redo',
    'publish', 'zoom_out', 'arrow_left', 'html', 'token', 'switch_access_shortcut', 'arrow_circle_left',
    'fullscreen_exit', 'sort_by_alpha', 'delete_sweep', 'indeterminate_check_box', 'first_page', 'view_timeline',
    'keyboard_double_arrow_up', 'settings_backup_restore', 'assistant_navigation', 'arrow_drop_down_circle',
    'sync_problem', 'clear_all', 'density_medium', 'heart_plus', 'filter_alt_off', 'last_page', 'expand',
    'subdirectory_arrow_right', 'unfold_less', 'arrow_outward', 'download_done', '123', 'swipe_left',
    'saved_search', 'place_item', 'system_update_alt', 'maximize', 'output', 'javascript', 'search_off',
    'select_all', 'swipe_up', 'fit_screen', 'check_small', 'dynamic_form', 'hide_source', 'swipe_right',
    'browse_gallery', 'switch_access_shortcut_add', 'css', 'density_small', 'assistant_direction',
    'file_upload', 'move_up', 'youtube_searched_for', 'swap_horizontal_circle', 'data_thresholding',
    'install_mobile', 'move_down', 'abc', 'dataset_linked', 'restore_from_trash', 'enable', 'install_desktop',
    'keyboard_command_key', 'view_kanban', 'reply_all', 'switch_left', 'browse_activity', 'compress',
    'swipe_down', 'swap_vertical_circle', 'remove_done', 'filter_list_off', 'apps_outage', 'switch_right',
    'hide', 'swipe_vertical', 'more_up', 'sync_disabled', 'keyboard_control_key', 'pinch', 'eject',
    'key_off', 'php', 'subdirectory_arrow_left', 'star_rate', 'view_cozy', 'do_not_disturb_off',
    'transcribe', 'send_time_extension', 'width_normal', 'view_comfy_alt', 'heart_minus', 'share_reviews',
    'width_full', 'unfold_more_double', 'file_download_off', 'view_compact_alt', 'extension_off',
    'open_in_new_off', 'check_indeterminate_small', 'more_down', 'width_wide', 'repartition',
    'swipe_left_alt', 'swipe_down_alt', 'swipe_up_alt', 'cycle', 'swipe_right_alt', 'unfold_less_double',
    'keyboard_option_key', 'person', 'person_add', 'account_circle', 'group', 'groups', 'share', 'thumb_up',
    'public', 'person_off', 'face', 'people', 'support_agent', 'handshake', 'face_6', 'account_box',
    'person_remove', 'check_circle_outline', 'sentiment_satisfied', 'rocket_launch', 'group_add', 'workspace_premium',
    'psychology', 'shapes', 'verified', 'emoji_events', 'travel_explore', 'diversity_3', 'quiz', 'report',
    'sentiment_very_satisfied', 'military_tech', 'thumb_down', 'gavel', 'sentiment_dissatisfied', 'recycling',
    'diamond', 'monitor_heart', 'person_add_alt', 'notifications', 'warning', 'help', 'info', 'mail', 'call',
    'edit', 'date_range', 'schedule', 'event', 'calendar_today', 'calendar_month', 'movie', 'movie_filter',
    'local_movies', 'theaters', 'camera', 'camera_alt', 'videocam', 'photo_camera', 'image', 'photo',
    'music_note', 'mic', 'headset', 'volume_up', 'play_arrow', 'pause', 'stop', 'skip_next', 'skip_previous',
    'fast_forward', 'fast_rewind', 'replay', 'repeat', 'shuffle', 'equalizer', 'radio', 'podcasts', 'album',
    'library_music', 'playlist_add', 'queue_music', 'explicit', 'sd', 'hd', '4k', 'closed_caption',
    'surround_sound', 'music_off', 'star_border', 'star_outline', 'bolt', 'offline_bolt', 'electric_bolt',
    'energy_savings_leaf', 'directions_car', 'directions_bus', 'flight', 'train', 'local_shipping',
    'two_wheeler', 'pedal_bike', 'directions_boat', 'navigation', 'map', 'place', 'near_me', 'location_on',
    'restaurant', 'restaurant_menu', 'local_cafe', 'local_dining', 'celebration', 'cake', 'nightlife',
    'local_bar', 'liquor', 'sports_bar', 'wine_bar', 'emoji_food_beverage', 'icecream', 'ramen_dining',
    'pizza', 'bakery_dining', 'shopping_bag', 'shopping_cart', 'receipt', 'credit_card', 'attach_money',
    'euro', 'currency_pound', 'currency_yen', 'currency_rupee', 'paid', 'account_balance', 'analytics',
    'insights', 'trending_up', 'trending_down', 'leaderboard', 'timeline', 'query_stats', 'bug_report',
    'code', 'terminal', 'developer_mode', 'developer_board', 'memory', 'router', 'cast', 'device_hub',
    'developer_board_off', 'videogame_asset', 'stadia_controller', 'gamepad', 'joystick', 'mouse',
    'keyboard', 'laptop', 'desktop_windows', 'smartphone', 'tablet', 'watch', 'speaker', 'headphones',
    'scanner', 'printer', 'hub', 'power', 'power_off', 'battery_full', 'battery_alert', 'charging_station',
    'wifi', 'signal_cellular_alt', 'bluetooth', 'nfc', 'usb', 'sd_storage', 'sim_card', 'phonelink_ring',
    'security', 'shield', 'lock', 'lock_open', 'visibility', 'visibility_off', 'fingerprint', 'key',
    'password', 'vpn_key', 'admin_panel_settings', 'policy', 'gpp_good', 'gpp_bad', 'fact_check',
    'verified_user', 'report_gmailerrorred'
];
